//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bæta við áfanga.
        /// </summary>
        internal static string Addcourse {
            get {
                return ResourceManager.GetString("Addcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stofna áfanga.
        /// </summary>
        internal static string AddCourseTitle {
            get {
                return ResourceManager.GetString("AddCourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tengja notendur við þennan áfanga.
        /// </summary>
        internal static string AddToCourse {
            get {
                return ResourceManager.GetString("AddToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bæta við notanda.
        /// </summary>
        internal static string Adduser {
            get {
                return ResourceManager.GetString("Adduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stofna notanda.
        /// </summary>
        internal static string AddUserTitle {
            get {
                return ResourceManager.GetString("AddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Óskiluð verkefni.
        /// </summary>
        internal static string AssignmentsDue {
            get {
                return ResourceManager.GetString("AssignmentsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til baka.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staðfesta Lykilorð:.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nafn áfanga:.
        /// </summary>
        internal static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áfangi verður að hafa nafn.
        /// </summary>
        internal static string CourseNameRequired {
            get {
                return ResourceManager.GetString("CourseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önn:.
        /// </summary>
        internal static string CourseSemester {
            get {
                return ResourceManager.GetString("CourseSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heiti áfanga.
        /// </summary>
        internal static string CourseTableName {
            get {
                return ResourceManager.GetString("CourseTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennsluár:.
        /// </summary>
        internal static string CourseYear {
            get {
                return ResourceManager.GetString("CourseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tölvupóstfang:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Því miður kom upp villa við meðhöndlun  fyrirspurnarinnar þinnar. Við biðjumst forláts á þessu og þeim óþægindum sem að  þetta kann að hafa valdið þér.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullt nafn:.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halló.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gera Notanda að kerfisstjóra.
        /// </summary>
        internal static string MakeAdmin {
            get {
                return ResourceManager.GetString("MakeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yfirlit.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lykilorð:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerfisstjóraréttindi fjarlægð.
        /// </summary>
        internal static string RemoveAdmin {
            get {
                return ResourceManager.GetString("RemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrifið til að leita.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennitala:.
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áfangar sem nemandi.
        /// </summary>
        internal static string StudentCourses {
            get {
                return ResourceManager.GetString("StudentCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staðfesta.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áfangar sem kennari.
        /// </summary>
        internal static string TeacherCourses {
            get {
                return ResourceManager.GetString("TeacherCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennarar.
        /// </summary>
        internal static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halló heimur.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notendanafn :.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heiti notanda.
        /// </summary>
        internal static string UserTableName {
            get {
                return ResourceManager.GetString("UserTableName", resourceCulture);
            }
        }
    }
}
